### ISSUE TITLE
How to visualize the generated .vtk files?

### ISSUE THREAD

**Issue by yiroro** [williamhunter/ToPy#35]
I tried to open the generated .vtk files (iteration results) in GMSH but failed. The error message is:

> Error: Unknown type of cell 11

Is it a common error? I also wrote a python script to render them as point cloud. It's OK, but I don't know how to render them as voxels and I also prefer a simpler way. How do you visualize the results usually?

**Comment by williamhunter** [comment]
Hi,

You must use Paraview or Mayavi to view the VTK files. Gmsh can only handle
a small subset of VTK files.

William

**Comment by yiroro** [comment]
I see. Thank you very much!
