### ISSUE TITLE
no output in terminal

### ISSUE THREAD

**Issue by Robou** [williamhunter/ToPy#36]
Hello, I am using `Ubuntu 14.04` and my Topy installation is working: I get the expected result images in the mbb_beam example, and don't get any errors.
But I don't get any output in the terminal (standard ubuntu shell terminal).

I saw in the wiki [here](https://github.com/williamhunter/topy/wiki/Tutorials#terminal-output) that we should see the results in output.
I don't have any log file created either.

I don't know python language. I have `Python 2.7.6` installed, but maybe I did not install all the [dependencies](https://github.com/williamhunter/topy/blob/master/INSTALL.md) very well. For example, `pysparse` was installed using an ubuntu package, and not installed from pip : `sudo apt-get install python-sparse` ([from here](https://launchpad.net/ubuntu/utopic/+package/python-sparse))

Is ther anything to activate the output or is it an issue?

**Comment by williamhunter** [comment]
I don't come here often anymore, sorry for the *very* late reply.

Should work out of the box, it's not a ToPy problem. You can try to direct the terminal output to a file by doing
`python optimise.py your_tpd_file.tpd > output.txt`
