### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by lychan110** [williamhunter/ToPy#38]
I'm getting the following error running the MBB example on Windows. It looks like running optimise.py the first time to create the stiffness matrices doesn't work for me.

![topy_error](https://user-images.githubusercontent.com/35710472/41874386-cd6938ac-7895-11e8-93f8-839ba9c5f5e5.PNG)

**Comment by ISosnovik** [comment]
Please use version [0.3.2](https://github.com/williamhunter/topy/releases/tag/v0.3.2) 
It is stable. The current version is actually corrupted by the previous commit

**Comment by lychan110** [comment]
Great, thank you!
