### ISSUE TITLE
Way to export stress tensor results?

### ISSUE THREAD

**Issue by manuel1618** [williamhunter/ToPy#43]
Hi there,
more a wish than an issue. But is it possible to export stress tensor results? 

Thanks in advance!

**Comment by williamhunter** [comment]
Not in its current state, but you'd be able to code it...

**Comment by manuel1618** [comment]
if you could give me a hint where to start, I would be happy to do so!

**Comment by williamhunter** [comment]
Can you give an example of how you would expect to use it, say, if it was already built into ToPy? In other words, what is your expected usage?

**Comment by manuel1618** [comment]
I want to use this for the geometry reconstruction process.

**Comment by williamhunter** [comment]
Sorry, not clear enough what the requirement is, I'm also not actively mainlining ToPy anymore.
