### ISSUE TITLE
Replace pysparse with scipy?

### ISSUE THREAD

**Issue by guozifeng91** [williamhunter/ToPy#44]
The pysparse library seems not being maintained anymore, the one that are available cannot adapt the current version of numpy. maybe it is necessary to replace it by some other well-maintained sparse algebra library such as scipy?

**Comment by guozifeng91** [comment]
I raise this as I am using windows and cannot find a runnable pysparse library, which similar with this issue: https://github.com/PythonOptimizers/pysparse/issues/4 . I tried several combinations of different version numpy and pysparse, and eventually i still cannot solve it. I went through the source code and seems all the solving methods used by topy are also available via scipy. so..... just a suggestion.

**Comment by williamhunter** [comment]
I don't maintain ToPy anymore. I tried SciPy long ago (about 10 years ago),
and back then it was way too slow. I don't know what it is like nowadays.

I guess I can have look at some point, I'm surprised people still use ToPy,
so perhaps I should consider it...

**Comment by zhengtn** [comment]
> 
> 
> I raise this as I am using windows and cannot find a runnable pysparse library, which similar with this issue: [PythonOptimizers/pysparse#4](https://github.com/PythonOptimizers/pysparse/issues/4) . I tried several combinations of different version numpy and pysparse, and eventually i still cannot solve it. I went through the source code and seems all the solving methods used by topy are also available via scipy. so..... just a suggestion.

So we can replace pysparse with scipy? Is the results the same？because I met many problems in installing pypsarse.

**Comment by CcCc1996** [comment]
> > I raise this as I am using windows and cannot find a runnable pysparse library, which similar with this issue: [PythonOptimizers/pysparse#4](https://github.com/PythonOptimizers/pysparse/issues/4) . I tried several combinations of different version numpy and pysparse, and eventually i still cannot solve it. I went through the source code and seems all the solving methods used by topy are also available via scipy. so..... just a suggestion.
> 
> So we can replace pysparse with scipy? Is the results the same？because I met many problems in installing pypsarse.

I also met this problem, I solved by use the numpy (version - 1.15)  and pysparse (version - 1.3). I hope this will help you.
