### ISSUE TITLE
error when running the example problem

### ISSUE THREAD

**Issue by amiracoder** [williamhunter/ToPy#45]
when trying to run the example file, I get the following error message:
`raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
`
any idea how I can solve this?

**Comment by mlaradji** [comment]
I faced the same issue on `topy=0.2.3`. In my case, downgrading `numpy` from `1.16.5` to `1.14.6` resolved it. (https://github.com/automl/auto-sklearn/issues/667#issuecomment-486629824)
