### ISSUE TITLE
Flesh out Example wiki page

### ISSUE THREAD

**Issue by williamhunter** [williamhunter/ToPy#5]
Show all the results from the source's examples directory.

**Comment by MsURGZI** [comment]
Not sure if it's what you're looking for, but here there is several gifs made about some examples I did run.
- [beam_2d_reci](https://imgur.com/a/4GV8t)
- [topy_beam_2d_reci_10_iters](http://imgur.com/a/Wc7sz)
- [topy_beam_2d_reci_gsf](https://imgur.com/a/iJNT4)
- [topy_beam_2d_reci_gsf_fine](https://imgur.com/a/Qrjgy)
- With the help of some others scripts (like [this one](https://gist.github.com/thewtex/8263132) and [this one](https://netfabb.azurewebsites.net/), I did get a good STL, available here.
  I've been running the examples one after the other, and now I'm been running the "beam_3d" so I don't have any result yet. I will post it, like the others, on imgur.

I did put the examples [here also](https://github.com/MsURGZI/topy/commit/a9c4849308bbbdf035c3b40925c12842de149d93), but as I'm quite new to the github usage, I'm a bit learning and I just get confused.

**Comment by williamhunter** [comment]
Thanks, added the fine res one.
